name: sudoku
registered_version: Sudoku-very-easy-v0

network:
    key_size: 64
    num_heads: 4
    policy_layers: [128]
    value_layers: [128]

training:
    num_epochs: 100
    num_learner_steps_per_epoch: 500
    n_steps: 20
    total_batch_size: 128

evaluation:
    eval_total_batch_size: 200
    greedy_eval_total_batch_size: 200

a2c:
    normalize_advantage: False
    discount_factor: 0.997
    bootstrapping_factor: 0.95
    l_pg: 1.0
    l_td: 1.0
    l_en: 0.01
    learning_rate: 5e-4
